In [1]:
import numpy as np
import pandas as pd

import sys

import datetime as dt
import _pickle as pickle

In [2]:
ld = pd.read_csv('listday.csv').dropna(axis=0)
# 筛选上市超过240天，未退市, 未ST
ld = ld[ld.start_date.apply(lambda x: dt.datetime.strptime(x, '%Y-%m-%d'))<(dt.datetime.now()-dt.timedelta(240))]
ld = ld[ld.end_date.apply(lambda x:dt.datetime.strptime(x, "%Y-%m-%d"))>dt.datetime.now()]
ld = ld[ld.display_name.apply(lambda x: 'ST' not in x)]

In [3]:
# SOE = pd.read_csv('399955.csv').sort_values(by=['start_date','stock_code']).set_index(['start_date', 'stock_code'])

In [4]:
# SOE_index = list(set(pd.read_csv('399955.csv').stock_code.values))
# pd.Series(SOE_index).sort_values().to_csv('issoe.csv', index=None)

In [5]:
d = pd.read_csv('399955.csv')
d = d.set_index(['start_date','stock_code']).unstack().index_code
d.index = [dt.datetime.strptime(x.split(' ')[0], '%d/%m/%Y') for x in d.index]
d.sort_index(inplace=True)

In [127]:
d.T ##需要加入soe到daily中，还未完成

,2011-05-31,2011-06-30,2011-07-29,2011-08-31,2011-09-30,2011-10-31,2011-11-30,2011-12-30,2012-01-31,2012-02-29,...,2021-01-29,2021-02-26,2021-03-31,2021-04-30,2021-05-31,2021-06-30,2021-07-30,2021-08-31,2021-09-30,2021-10-29
stock_code,,,,,,,,,,,,,,,,,,,,,
000002.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,...,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ
000006.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,...,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ
000008.SZ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ
000011.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,...,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ
000012.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
688396.SH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ
688505.SH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ
688569.SH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,399955.SZ,399955.SZ,399955.SZ
688586.SH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,399955.SZ,399955.SZ,399955.SZ
688589.SH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,399955.SZ,399955.SZ,399955.SZ,399955.SZ

In [85]:
data = pd.read_csv('trading_data.csv').sort_values(by=['trade_date','stock_code']).set_index(['trade_date', 'stock_code'])
data = data.unstack(level=0).loc[ld.stock_code,:]
# data.head()

In [84]:
# data.unstack(level=0).loc[ld.stock_code,:]

                  low                                                         \
trade_date 2014-01-02 2014-01-03 2014-01-06 2014-01-07 2014-01-08 2014-01-09
stock_code
000001.SZ       12.05      11.78      11.50      11.51      11.53      11.65
000002.SZ        7.92       7.76       7.37       7.34       7.38       7.35
000004.SZ       11.45      11.68      11.73      11.81      12.02      12.10
000006.SZ        4.84       4.71       4.41       4.41       4.37       4.13
000008.SZ        8.93       8.90       8.43       8.32       8.10       8.06
...               ...        ...        ...        ...        ...        ...
688777.SH         NaN        NaN        NaN        NaN        NaN        NaN
688788.SH         NaN        NaN        NaN        NaN        NaN        NaN
688819.SH         NaN        NaN        NaN        NaN        NaN        NaN
688981.SH         NaN        NaN        NaN        NaN        NaN        NaN
689009.SH         NaN        NaN        NaN        NaN        NaN        NaN

                                                        ...       high  \
trade_date 2014-01-10 2014-01-13 2014-01-14 2014-01-15  ... 2021-10-29
stock_code                                              ...
000001.SZ       11.66      11.49      11.45      11.56  ...      19.74
000002.SZ        7.37       7.06       7.13       7.12  ...      19.13
000004.SZ       11.30      11.15      11.27      11.34  ...      16.83
000006.SZ        4.12       4.13       4.16       4.25  ...       4.17
000008.SZ        7.83       8.00       8.35       8.46  ...       2.19
...               ...        ...        ...        ...  ...        ...
688777.SH         NaN        NaN        NaN        NaN  ...      86.37
688788.SH         NaN        NaN        NaN        NaN  ...     133.05
688819.SH         NaN        NaN        NaN        NaN  ...      41.11
688981.SH         NaN        NaN        NaN        NaN  ...      55.38
689009.SH         NaN        NaN        NaN        NaN  ...      64.90

                                                                              \
trade_date 2021-11-01 2021-11-02 2021-11-03 2021-11-04 2021-11-05 2021-11-08
stock_code
000001.SZ       19.73      19.49      18.24      18.10      18.00      17.81
000002.SZ       18.40      18.29      18.09      18.14      18.00      18.60
000004.SZ       16.94      16.94      16.91      16.95      17.39      17.34
000006.SZ        4.19       4.17       4.13       4.14       4.12       4.10
000008.SZ        2.18       2.18       2.14       2.14       2.13       2.12
...               ...        ...        ...        ...        ...        ...
688777.SH       86.86      86.00      87.80      90.99      90.98      89.06
688788.SH      135.26     140.20     138.88     139.80     139.38     134.99
688819.SH       43.29      43.18      42.67      43.66      43.73      45.09
688981.SH       55.48      57.07      57.17      57.68      58.39      56.90
689009.SH       64.10      65.66      65.99      65.48      64.99      63.59


trade_date 2021-11-09 2021-11-10 2021-11-11
stock_code
000001.SZ       17.65      17.47      18.43
000002.SZ       18.31      19.01      20.84
000004.SZ       17.58      17.85      17.59
000006.SZ        4.10       4.16       4.30
000008.SZ        2.13       2.12       2.16
...               ...        ...        ...
688777.SH       88.53      87.81      89.61
688788.SH      136.50     138.45     141.00
688819.SH       45.30      44.65      44.75
688981.SH       59.55      59.53      60.17
689009.SH       63.79      63.70      64.18

[3984 rows x 7656 columns]

In [6]:
def fillind(x):
    x = x.sort_index()
    if x.isna().all():
        x.fillna(9351111.0, inplace=True) #'wfl1111, 九宫格键盘'
    else:
        x.fillna(method='bfill', axis=0, inplace=True)
        x.fillna(method='ffill', axis=0, inplace=True)
        
    return x
        

daily_data_tra = pd.read_csv('trading_data.csv').set_index(['trade_date', 'stock_code']) # 无na值
daily_data_ind = pd.read_csv('industry.csv').drop(columns=['Unnamed: 0']).set_index(['trade_date', 'stock_code'],).groupby('stock_code').apply(lambda x: x.fillna(method='bfill'))
daily_data_ma = pd.read_csv('test-2.csv', header=0).set_index(['trade_date', 'stock_code']) #pe ps值缺失， 使用均值方式填充，turnover=0代表当日未交易，drop
# daily_data = pd.merge(daily_data_ind, daily_data_ma, on=['trade_date', 'stock_code']).rename(columns={'sw_l1':'indus_index'})
# daily_data = pd.merge(daily_data, daily_data_tra, on=['trade_date', 'stock_code'])

In [7]:
# daily_data_ma.pe_ratio = daily_data_ma.pe_ratio.groupby('stock_code').apply(lambda x: x.sort_index().interpolate())
# daily_data_ma.ps_ratio = daily_data_ma.ps_ratio.groupby('stock_code').apply(lambda x: x.sort_index().interpolate())

# 另外的方法是：将两个时序序列对一些因子做回归，得到回归系数来算缺失值。
# 这种方法偏误估计，但方差较小。
# daily_data_ma.dropna(axis=0, inplace=True)

In [8]:
# print(f'shape of daily_data_tra is {daily_data_tra.shape}')
# print(f'shape of daily_data_ind is {daily_data_ind.shape}')
# print(f'shape of daily_data_ma is {daily_data_ma.shape}')

In [9]:
# daily = pd.concat([daily_data_tra, daily_data_ind, daily_data_ma], axis=1).dropna(axis=0, subset=['turnover_ratio']).rename(columns={'sw_l1':'indus_index'})
daily = pd.concat([daily_data_tra.loc[daily_data_ma.index,:], daily_data_ind, daily_data_ma], axis=1).rename(columns={'sw_l1':'indus_index'})

daily.indus_index = daily.indus_index.groupby('stock_code').apply(lambda x: fillind(x))

In [ ]:
daily = daily.unstack(level=0).loc[ld.stock_code,:]
daily.dropna(axis=1, how='all', inplace=True)

KeyError: "None of [Index(['2014-01-02', '2014-01-03', '2014-01-06', '2014-01-07', '2014-01-08',\n       '2014-01-09', '2014-01-10', '2014-01-13', '2014-01-14', '2014-01-15',\n       ...\n       '2021-10-18', '2021-10-19', '2021-10-20', '2021-10-21', '2021-10-22',\n       '2021-10-25', '2021-10-26', '2021-10-27', '2021-10-28', '2021-10-29'],\n      dtype='object', name='trade_date', length=1905)] are in the [index]"

stock_code,000002.SZ,000006.SZ,000008.SZ,000011.SZ,000012.SZ,000014.SZ,000016.SZ,000019.SZ,000021.SZ,000024.SZ,...,688122.SH,688126.SH,688128.SH,688165.SH,688189.SH,688396.SH,688505.SH,688569.SH,688586.SH,688589.SH
2011-05-31,399955.SZ,399955.SZ,NaN,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-06-30,399955.SZ,399955.SZ,NaN,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-07-29,399955.SZ,399955.SZ,NaN,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-08-31,399955.SZ,399955.SZ,NaN,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-09-30,399955.SZ,399955.SZ,NaN,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-06-30,399955.SZ,399955.SZ,399955.SZ,399955.SZ,NaN,399955.SZ,399955.SZ,399955.SZ,399955.SZ,NaN,...,399955.SZ,399955.SZ,399955.SZ,NaN,399955.SZ,399955.SZ,399955.SZ,NaN,NaN,NaN
2021-07-30,399955.SZ,399955.SZ,399955.SZ,399955.SZ,NaN,399955.SZ,399955.SZ,399955.SZ,399955.SZ,NaN,...,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,NaN,NaN,399955.SZ
2021-08-31,399955.SZ,399955.SZ,399955.SZ,399955.SZ,NaN,399955.SZ,399955.SZ,399955.SZ,399955.SZ,NaN,...,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ
2021-09-30,399955.SZ,399955.SZ,399955.SZ,399955.SZ,NaN,399955.SZ,399955.SZ,399955.SZ,399955.SZ,NaN,...,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ
2021-10-29,399955.SZ,399955.SZ,399955.SZ,399955.SZ,NaN,399955.SZ,399955.SZ,399955.SZ,399955.SZ,NaN,...,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ,399955.SZ

In [15]:
k = set([key[0] for key in daily.columns])
for key in k:
    print(key,': ' ,daily.loc[:,(key, slice(None))].shape)

turnover_ratio :  (4016, 1905)
return_adj :  (4016, 1905)
high :  (4016, 1905)
pb_ratio :  (4016, 1905)
close :  (4016, 1905)
open :  (4016, 1905)
pe_ratio :  (4016, 1905)
indus_index :  (4016, 1905)
market_cap :  (4016, 1905)
ps_ratio :  (4016, 1905)
low :  (4016, 1905)
circulating_market_cap :  (4016, 1905)

In [ ]:
# 处理soe

In [ ]:
# 处理turnover=0的情况，利用市场和历史平均换手加权填充
t = daily.turnover_ratio.T
market = t.where(t!=0).mean(axis=1)
history = t.where(t!=0).mean(axis=0)

market = pd.DataFrame({stock:market for stock in t.columns})
history = pd.DataFrame({date:history for date in t.index}).T

q = 0.6
fillval = market*q+(1-q)*history
t = t.where(t!=0, fillval)
daily.turnover_ratio = t.T

In [155]:
daily.to_csv('arranged_data_20140102_20211029.csv')

In [ ]:
# daily.loc[(slice(None), '689009.SH'),:]

In [ ]:
# file = 'model_output_000985_20211020_1.pkl'

# with open(file, 'rb') as f:
#     d = pickle.load(f)
    
# d = pd.DataFrame(d, columns=['date', 'code', 'xxx']).set_index(['date','code'])
# d.unstack()

In [14]:
daily_data = pd.read_csv('arranged_data_20140102_20211029.csv').set_index(['trade_date', 'stock_code']).sort_index()
daily_data['soe'] = np.zeros((daily_data.shape[0],))
issoe = pd.read_csv('issoe.csv').values

In [30]:
def updatesoe(x):
    if x.name in issoe:
        x.soe = 1
    return x

daily_data = daily_data.groupby('stock_code').apply(updatesoe)

In [60]:
daily_data.to_csv('arranged_data_20140102_20211029.csv')

array([['000002.SZ'],
       ['000006.SZ'],
       ['000008.SZ'],
       ...,
       ['688569.SH'],
       ['688586.SH'],
       ['688589.SH']], dtype=object)

In [33]:
## 对于turnover=0 or nan的部分做填充

daily_data = pd.read_csv('arranged_data_20140102_20211029.csv').set_index(['trade_date', 'stock_code']).sort_index()

In [34]:
daily_data.turnover_ratio.unstack()

stock_code,000001.SZ,000002.SZ,000004.SZ,000005.SZ,000006.SZ,000007.SZ,000008.SZ,000009.SZ,000010.SZ,000011.SZ,...,688787.SH,688788.SH,688789.SH,688793.SH,688798.SH,688799.SH,688800.SH,688819.SH,688981.SH,689009.SH
trade_date,,,,,,,,,,,,,,,,,,,,,
2014-01-02,0.8786,0.5015,1.1582,0.3283,0.6593,1.7754,0.6285,0.9996,1.5796,0.7468,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-01-03,0.9884,0.5586,3.3142,0.2477,0.7833,1.1818,0.6091,1.0972,4.1233,1.3163,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-01-06,1.0440,1.2728,8.4014,0.4767,1.3019,1.8159,1.1683,0.8792,3.2292,1.0830,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-01-07,0.6069,0.6213,3.4688,0.6994,0.5751,2.4869,0.6459,0.4718,1.3270,0.8247,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2014-01-08,0.8210,0.6144,2.1785,0.4159,0.5968,1.5478,0.7590,0.9042,1.5441,1.1885,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-10-25,0.3766,1.7519,1.3576,0.7664,0.9362,3.7190,0.6047,7.5946,0.6364,1.2766,...,3.6153,0.9991,0.8387,2.0253,0.8027,1.4370,2.9465,3.0216,1.2236,3.3587
2021-10-26,0.3364,1.6020,4.4382,0.7865,0.3201,1.6915,0.5412,10.5800,0.9090,0.9764,...,1.6818,1.2791,1.0827,1.6674,0.8254,1.6278,3.8330,3.3314,1.1994,4.4054
2021-10-27,0.3543,0.9761,3.7213,0.7793,0.3770,2.1542,0.4194,9.1474,2.8074,0.9678,...,3.7088,2.6308,1.1376,2.1451,6.0354,3.5157,2.8695,3.7465,0.9256,3.3823
2021-10-28,0.3190,1.0722,1.5386,0.8115,0.3359,1.1938,0.6811,7.4789,1.7926,0.7301,...,2.3477,2.3010,1.7520,4.1292,3.3856,3.0354,5.5929,3.7322,0.8235,2.6286
2021-10-29,0.2782,2.5180,1.4502,0.8259,0.2787,2.8930,0.4083,5.0587,0.8326,0.7251,...,1.8360,1.4619,1.1082,2.0872,1.3042,1.7986,10.1893,1.7861,1.1187,0.3066

In [153]:
t = daily.turnover_ratio.T
market = t.where(t!=0).mean(axis=1)
history = t.where(t!=0).mean(axis=0)

market = pd.DataFrame({stock:market for stock in t.columns})
history = pd.DataFrame({date:history for date in t.index}).T

q = 0.6
fillval = market*q+(1-q)*history
t = t.where(t!=0, fillval)
daily.turnover_ratio = t.T

In [154]:
daily

                  low                                                         \
trade_date 2014-01-02 2014-01-03 2014-01-06 2014-01-07 2014-01-08 2014-01-09
stock_code
000001.SZ       12.05      11.78      11.50      11.51      11.53      11.65
000002.SZ        7.92       7.76       7.37       7.34       7.38       7.35
000004.SZ       11.45      11.68      11.73      11.81      12.02      12.10
000006.SZ        4.84       4.71       4.41       4.41       4.37       4.13
000008.SZ        8.93       8.90       8.43       8.32       8.10       8.06
...               ...        ...        ...        ...        ...        ...
688777.SH         NaN        NaN        NaN        NaN        NaN        NaN
688788.SH         NaN        NaN        NaN        NaN        NaN        NaN
688819.SH         NaN        NaN        NaN        NaN        NaN        NaN
688981.SH         NaN        NaN        NaN        NaN        NaN        NaN
689009.SH         NaN        NaN        NaN        NaN        NaN        NaN

                                                        ... return_adj  \
trade_date 2014-01-10 2014-01-13 2014-01-14 2014-01-15  ... 2021-10-18
stock_code                                              ...
000001.SZ       11.66      11.49      11.45      11.56  ...  -0.018820
000002.SZ        7.37       7.06       7.13       7.12  ...  -0.037459
000004.SZ       11.30      11.15      11.27      11.34  ...  -0.035158
000006.SZ        4.12       4.13       4.16       4.25  ...  -0.002252
000008.SZ        7.83       8.00       8.35       8.46  ...   0.027149
...               ...        ...        ...        ...  ...        ...
688777.SH         NaN        NaN        NaN        NaN  ...  -0.048874
688788.SH         NaN        NaN        NaN        NaN  ...  -0.028000
688819.SH         NaN        NaN        NaN        NaN  ...   0.015629
688981.SH         NaN        NaN        NaN        NaN  ...  -0.015096
689009.SH         NaN        NaN        NaN        NaN  ...   0.009762

                                                                              \
trade_date 2021-10-19 2021-10-20 2021-10-21 2021-10-22 2021-10-25 2021-10-26
stock_code
000001.SZ    0.014515  -0.016863   0.039501   0.002000   0.003992  -0.003479
000002.SZ    0.000000  -0.014778   0.036500   0.028944  -0.034693  -0.042254
000004.SZ    0.007288  -0.018088  -0.014211   0.004805  -0.004782  -0.057128
000006.SZ    0.002257  -0.006757   0.009070   0.000000  -0.040449  -0.009368
000008.SZ   -0.004405   0.000000   0.000000  -0.013274   0.004484   0.008929
...               ...        ...        ...        ...        ...        ...
688777.SH    0.031583   0.055522  -0.039595  -0.014262   0.016292   0.019978
688788.SH    0.037118   0.007547  -0.022162   0.001342   0.001104  -0.013550
688819.SH    0.018064   0.012486  -0.020338  -0.024072   0.029645  -0.012747
688981.SH    0.005910  -0.004406  -0.009404   0.038533  -0.005377  -0.008830
689009.SH   -0.009165  -0.024328  -0.011948  -0.005258  -0.088399  -0.028845


trade_date 2021-10-27 2021-10-28 2021-10-29
stock_code
000001.SZ   -0.006484  -0.010040  -0.011156
000002.SZ   -0.003043  -0.026958  -0.048092
000004.SZ   -0.067950   0.004253   0.015729
000006.SZ   -0.018913  -0.016867   0.022059
000008.SZ   -0.017699  -0.031532   0.013953
...               ...        ...        ...
688777.SH   -0.039878  -0.036281   0.085435
688788.SH    0.085689  -0.051048   0.017441
688819.SH   -0.043188  -0.058167   0.006670
688981.SH   -0.016000   0.002217   0.014749
689009.SH   -0.058209   0.014263   0.000000

[4016 rows x 22860 columns]

In [74]:

daily_data.loc[:,'turnover_ratio'].fillna(fillval.stack(), inplace=True)

In [76]:
daily_data.turnover_ratio[daily_data.turnover_ratio.isna()]

Series([], Name: turnover_ratio, dtype: float64)

In [80]:
daily_data.turnover_ratio.isna().any()

False